typedef enum
{
  CONFIGITEM_SERIAL_NUMBER = 0,           /
  CONFIGITEM_CRYPT_KEY,                   /
  CONFIGITEM_HARDWARE_OPTIONS_MFG,        /
  CONFIGITEM_HARDWARE_OPTIONS,            /
  CONFIGITEM_NVRAM_CHANGES,               /

  CONFIGITEM_NVRAMDIRTY,                  /
  CONFIGITEM_NVRAM_WV,                    /
  CONFIGITEM_ENABLE_WDT,                  /
  CONFIGITEM_EARLY_ACK,                   /
  CONFIGITEM_CONSOLE_AES_ONLY,            /
  CONFIGITEM_RADIO_AES_ONLY,              /
  CONFIGITEM_NDRLE,                       /
  CONFIGITEM_SOMF,                        /
  CONFIGITEM_NOGAF,                       /
  CONFIGITEM_CARD_READER_POWER,           /
  CONFIGITEM_PROX_ENABLE,                 /
  CONFIGITEM_CKSUMCONFIG,                 /
  CONFIGITEM_DAILY_BATTERY_CHECK,         /
  CONFIGITEM_DAILY_BATTERY_CHECK_HOUR,    /
  CONFIGITEM_BATTERY_LOW,                 /

  CONFIGITEM_LRU_HEAD,                    /
  CONFIGITEM_LRU_TAIL,                    /
  CONFIGITEM_RTC_CALIBRATION,             /
  CONFIGITEM_ACVREQUESTER,                /
  CONFIGITEM_LOCAL_LED,                   /

  CONFIGITEM_ERRCNT_XORLEN,               /
  CONFIGITEM_ERRCNT_CRC,                  /
  CONFIGITEM_ERRCNT_NOTSIGIL,             /
  CONFIGITEM_ERRCNT_TIMEOUT,              /
  CONFIGITEM_ERRCNT_TOOLONG,              /
  CONFIGITEM_ERRCNT_TOOSHORT,             /
  CONFIGITEM_ERRCNT_HITDEFAULT,           /
  CONFIGITEM_ERRCNT_OVERRUN,              /
  CONFIGITEM_ERRCNT_UARTFE,               /
  CONFIGITEM_ERRCNT_UARTOE,               /

  CONFIGITEM_DST_SET,                     /
  CONFIGITEM_DST_MODE,                    /
  CONFIGITEM_DST_FORWARD_MONTH,           /
  CONFIGITEM_DST_FORWARD_DOM,             /
  CONFIGITEM_DST_FORWARD_OOD,             /
  CONFIGITEM_DST_FORWARD_DOW,             /
  CONFIGITEM_DST_FORWARD_HOUR,            /
  CONFIGITEM_DST_FORWARD_MINUTE,          /
  CONFIGITEM_DST_FORWARD_ADJUST,          /
  CONFIGITEM_DST_BACK_MONTH,              /
  CONFIGITEM_DST_BACK_DOM,                /
  CONFIGITEM_DST_BACK_OOD,                /
  CONFIGITEM_DST_BACK_DOW,                /
  CONFIGITEM_DST_BACK_HOUR,               /
  CONFIGITEM_DST_BACK_MINUTE,             /
  CONFIGITEM_DST_BACK_ADJUST,             /

  CONFIGITEM_EVENTLOG_ZEROMEM,            /
  CONFIGITEM_EVENTLOG_BEGIN,              /
  CONFIGITEM_EVENTLOG_RECORD,             /
  CONFIGITEM_EVENTLOG_ENTRIES,            /
  CONFIGITEM_EVENTLOG_WARNDEVICE,         /
  CONFIGITEM_EVENTLOG_WARNEVERY,          /
  CONFIGITEM_EVENTLOG_RMTDEVICE,          /

  CONFIGITEM_DECLINEDLOG_ZEROMEM,         /
  CONFIGITEM_DECLINEDLOG_BEGIN,           /
  CONFIGITEM_DECLINEDLOG_RECORD,          /
  CONFIGITEM_DECLINEDLOG_ENTRIES,         /
  CONFIGITEM_DECLINEDLOG_WARNDEVICE,      /
  CONFIGITEM_DECLINEDLOG_WARNEVERY,       /
  CONFIGITEM_DECLINEDLOG_RMTDEVICE,       /

  CONFIGITEM_ALARMLOG_ZEROMEM,            /
  CONFIGITEM_ALARMLOG_BEGIN,              /
  CONFIGITEM_ALARMLOG_RECORD,             /
  CONFIGITEM_ALARMLOG_ENTRIES,            /
  CONFIGITEM_ALARMLOG_WARNDEVICE,         /
  CONFIGITEM_ALARMLOG_WARNEVERY,          /
  CONFIGITEM_ALARMLOG_RMTDEVICE,          /

  CONFIGITEM_VISIBLE_FEEDBACK,            /
  CONFIGITEM_AUDIBLE_FEEDBACK,            /
  CONFIGITEM_VISIBLE_INDICATORS,          /
  CONFIGITEM_AUDIBLE_INDICATORS,          /
  CONFIGITEM_2NDPINDURATION,              /
  CONFIGITEM_LOCKOUT_ATTEMPTS,            /
  CONFIGITEM_LOCKOUT_DURATION,            /
  CONFIGITEM_KEYPAD_INACTIVITY,           /
  CONFIGITEM_ICIDLE_DURATION,             /
  CONFIGITEM_WRITE_DECLINED_LOG,          /
  CONFIGITEM_LOW_BATTERY_INDICATOR,       /

  CONFIGITEM_PANIC_MODE,                  /

  CONFIGITEM_TIMEZONE_ENABLE,             /
  CONFIGITEM_EXCEPTION_ENABLE,            /
  CONFIGITEM_AUTOUNLOCK_ENABLE,           /

  CONFIGITEM_LOCK_PRIORITY_EMERGENCY,     /
  CONFIGITEM_LOCK_PRIORITY_SUPERVISOR,    /
  CONFIGITEM_LOCK_PRIORITY_USER,          /
  CONFIGITEM_LOCK_PRIORITY_PASSAGE,       /
  CONFIGITEM_LOCK_PRIORITY_PANIC,         /
  CONFIGITEM_LOCK_PRIORITY_LOCKOUT,       /
  CONFIGITEM_LOCK_PRIORITY_RELOCK,        /
  CONFIGITEM_LOCK_PRIORITY_BOLTTHROWN,    /
  CONFIGITEM_LOCK_PRIORITY_CONFIGCHANGE,  /
  CONFIGITEM_LOCK_PRIORITY_REMOTE,        /
  CONFIGITEM_LOCK_TYPE,                   /
  CONFIGITEM_DOUBLE_PULSE,                /
  CONFIGITEM_DOUBLE_DELAY,                /
  CONFIGITEM_MOTOR_DURATION,              /
  CONFIGITEM_MORTISE_TYPE,                /
  CONFIGITEM_UNLOCK_TIME,                 /
  CONFIGITEM_EXT_UNLOCK_TIME,             /
  CONFIGITEM_DOOR_AJAR_TIME,              /

  CONFIGITEM_SESSION_TIMEOUT,             /
  CONFIGITEM_RETRY_ON_TIMEOUT,            /

  CONFIGITEM_UNSOLICITED_ENCRYPT,         /
  CONFIGITEM_RMT_AUTH_TIMEOUT,            /
  CONFIGITEM_RMT_AUTH_DEVICE,             /
  CONFIGITEM_ALARM_DEVICE,                /
  CONFIGITEM_NOTIFY_DEVICE,               /
  CONFIGITEM_COMMUSER_DEVICE,             /
  CONFIGITEM_SCHEDULER_DEVICE,            /

  CONFIGITEM_SCHEDULER_TYPE,              /
  CONFIGITEM_SCHEDULER_AWAKE,             /
  CONFIGITEM_SCHEDULER_PERIOD,            /
  CONFIGITEM_SCHEDULER_HOD,               /
  CONFIGITEM_SCHEDULER_DOW,               /
  CONFIGITEM_SCHEDULER_DOM,               /
  CONFIGITEM_SCHEDULER_HM1,               /
  CONFIGITEM_SCHEDULER_HM2,               /
  CONFIGITEM_SCHEDULER_HM3,               /
  CONFIGITEM_SCHEDULER_HM4,               /

  CONFIGITEM_RADIO_TYPE,                  /
  CONFIGITEM_RADIO_MODE,                  /
  CONFIGITEM_RADIO_TIMEOUT,               /
  CONFIGITEM_RADIO_ATTEMPTS,              /
  CONFIGITEM_RADIO_HOUSEKEEPING,          /
  CONFIGITEM_RADIO_LEAPUSERNAME,          /
  CONFIGITEM_RADIO_LEAPPASSWORD,          /

  CONFIGITEM_INHIBIT_VOLTAGE,             /
  CONFIGITEM_LOW_VOLTAGE,                 /
  CONFIGITEM_PT_RANGE_1,                  /
  CONFIGITEM_PT_RANGE_2,                  /
  CONFIGITEM_PT_RANGE_3,                  /
  CONFIGITEM_PT_RANGE_4,                  /
  CONFIGITEM_PT_RANGE_5,                  /
  CONFIGITEM_PT_RANGE_6,                  /
  CONFIGITEM_PT_RANGE_7,                  /
  CONFIGITEM_PT_RANGE_8,                  /

  CONFIGITEM_MAGCARD_IFS,                 /
  CONFIGITEM_MAGCARD_FIELDS,              /
  CONFIGITEM_MAGCARD_OFFSET,              /
  CONFIGITEM_MAGCARD_DIGITS,              /

  CONFIGITEM_ALARMS,                      /
  CONFIGITEM_FILTERS,                     /
  CONFIGITEM_ALARMSTATE,                  /
  CONFIGITEM_DOORSTATE,                   /

  CONFIGITEM_DPACDEBUG,                   /
  CONFIGITEM_FAILOPENSECURE,              /

  CONFIGITEM_REPLACED_VOLTAGE,            /

  CONFIGITEM_RX_HELD_TIME,                /
  CONFIGITEM_PACKET_TIMEOUT,              /

  CONFIGITEM_EXTENDEDRESPONSE,            /
  CONFIGITEM_PASSAGEMODEINDICATOR,        /

  CONFIGITEM_PFMRETURNTIME,               /

  CONFIGITEM_LAST,                        /

  CONFIGITEM_MAGIC_FIRST = 239,           /
  CONFIGITEM_MAGIC_USERFIELD,             /
  CONFIGITEM_MAGIC_USERADD,               /
  CONFIGITEM_MAGIC_USERDELETE,            /
  CONFIGITEM_MAGIC_NVRAMBACKUP,           /
  CONFIGITEM_MAGIC_NVRAMRESTORE,          /
  CONFIGITEM_MAGIC_NVRAMERASE,            /
  CONFIGITEM_MAGIC_LAST                   /
}
