void
proto_register_ansi_tcap(void)
{

/
    static hf_register_info hf[] = {
	/
	{ &hf_ansi_tcapsrt_SessionId,
	  { "Session Id",
	    "ansi_tcap.srt.session_id",
	    FT_UINT32, BASE_DEC, NULL, 0x0,
	    "", HFILL }
	},
	{ &hf_ansi_tcapsrt_BeginSession,
	  { "Begin Session",
	    "ansi_tcap.srt.begin",
	    FT_FRAMENUM, BASE_NONE, NULL, 0x0,
	    "SRT Begin of Session", HFILL }
	},
	{ &hf_ansi_tcapsrt_EndSession,
	  { "End Session",
	    "ansi_tcap.srt.end",
	    FT_FRAMENUM, BASE_NONE, NULL, 0x0,
	    "SRT End of Session", HFILL }
	},
	{ &hf_ansi_tcapsrt_SessionTime,
	  { "Session duration",
	    "ansi_tcap.srt.sessiontime",
	    FT_RELATIVE_TIME, BASE_NONE, NULL, 0x0,
	    "Duration of the TCAP session", HFILL }
	},
	{ &hf_ansi_tcapsrt_Duplicate,
	  { "Request Duplicate",
	    "ansi_tcap.srt.duplicate",
	    FT_UINT32, BASE_DEC, NULL, 0x0,
	    "", HFILL }
	},

/
#line 1 "packet-ansi_tcap-hfarr.c"
    { &hf_ansi_tcap_national,
      { "national", "ansi_tcap.national",
        FT_INT32, BASE_DEC, NULL, 0,
        "ansi_tcap.T_national", HFILL }},
    { &hf_ansi_tcap_private,
      { "private", "ansi_tcap.private",
        FT_INT32, BASE_DEC, NULL, 0,
        "ansi_tcap.T_private", HFILL }},
    { &hf_ansi_tcap_national_01,
      { "national", "ansi_tcap.national",
        FT_INT32, BASE_DEC, NULL, 0,
        "ansi_tcap.INTEGER_M128_127", HFILL }},
    { &hf_ansi_tcap_private_01,
      { "private", "ansi_tcap.private",
        FT_INT32, BASE_DEC, NULL, 0,
        "ansi_tcap.INTEGER", HFILL }},
    { &hf_ansi_tcap_unidirectional,
      { "unidirectional", "ansi_tcap.unidirectional",
        FT_NONE, BASE_NONE, NULL, 0,
        "ansi_tcap.T_unidirectional", HFILL }},
    { &hf_ansi_tcap_queryWithPerm,
      { "queryWithPerm", "ansi_tcap.queryWithPerm",
        FT_NONE, BASE_NONE, NULL, 0,
        "ansi_tcap.T_queryWithPerm", HFILL }},
    { &hf_ansi_tcap_queryWithoutPerm,
      { "queryWithoutPerm", "ansi_tcap.queryWithoutPerm",
        FT_NONE, BASE_NONE, NULL, 0,
        "ansi_tcap.T_queryWithoutPerm", HFILL }},
    { &hf_ansi_tcap_response,
      { "response", "ansi_tcap.response",
        FT_NONE, BASE_NONE, NULL, 0,
        "ansi_tcap.T_response", HFILL }},
    { &hf_ansi_tcap_conversationWithPerm,
      { "conversationWithPerm", "ansi_tcap.conversationWithPerm",
        FT_NONE, BASE_NONE, NULL, 0,
        "ansi_tcap.T_conversationWithPerm", HFILL }},
    { &hf_ansi_tcap_conversationWithoutPerm,
      { "conversationWithoutPerm", "ansi_tcap.conversationWithoutPerm",
        FT_NONE, BASE_NONE, NULL, 0,
        "ansi_tcap.T_conversationWithoutPerm", HFILL }},
    { &hf_ansi_tcap_abort,
      { "abort", "ansi_tcap.abort",
        FT_NONE, BASE_NONE, NULL, 0,
        "ansi_tcap.T_abort", HFILL }},
    { &hf_ansi_tcap_identifier,
      { "identifier", "ansi_tcap.identifier",
        FT_BYTES, BASE_HEX, NULL, 0,
        "ansi_tcap.TransactionID", HFILL }},
    { &hf_ansi_tcap_dialoguePortion,
      { "dialoguePortion", "ansi_tcap.dialoguePortion",
        FT_NONE, BASE_NONE, NULL, 0,
        "ansi_tcap.DialoguePortion", HFILL }},
    { &hf_ansi_tcap_componentPortion,
      { "componentPortion", "ansi_tcap.componentPortion",
        FT_UINT32, BASE_DEC, NULL, 0,
        "ansi_tcap.ComponentSequence", HFILL }},
    { &hf_ansi_tcap_dialogPortion,
      { "dialogPortion", "ansi_tcap.dialogPortion",
        FT_NONE, BASE_NONE, NULL, 0,
        "ansi_tcap.DialoguePortion", HFILL }},
    { &hf_ansi_tcap_causeInformation,
      { "causeInformation", "ansi_tcap.causeInformation",
        FT_UINT32, BASE_DEC, VALS(ansi_tcap_T_causeInformation_vals), 0,
        "ansi_tcap.T_causeInformation", HFILL }},
    { &hf_ansi_tcap_abortCause,
      { "abortCause", "ansi_tcap.abortCause",
        FT_INT32, BASE_DEC, NULL, 0,
        "ansi_tcap.P_Abort_cause", HFILL }},
    { &hf_ansi_tcap_userInformation,
      { "userInformation", "ansi_tcap.userInformation",
        FT_NONE, BASE_NONE, NULL, 0,
        "ansi_tcap.UserAbortInformation", HFILL }},
    { &hf_ansi_tcap_version,
      { "version", "ansi_tcap.version",
        FT_BYTES, BASE_HEX, NULL, 0,
        "ansi_tcap.ProtocolVersion", HFILL }},
    { &hf_ansi_tcap_applicationContext,
      { "applicationContext", "ansi_tcap.applicationContext",
        FT_UINT32, BASE_DEC, VALS(ansi_tcap_T_applicationContext_vals), 0,
        "ansi_tcap.T_applicationContext", HFILL }},
    { &hf_ansi_tcap_integerApplicationId,
      { "integerApplicationId", "ansi_tcap.integerApplicationId",
        FT_INT32, BASE_DEC, NULL, 0,
        "ansi_tcap.IntegerApplicationContext", HFILL }},
    { &hf_ansi_tcap_objectApplicationId,
      { "objectApplicationId", "ansi_tcap.objectApplicationId",
        FT_OID, BASE_NONE, NULL, 0,
        "ansi_tcap.ObjectIDApplicationContext", HFILL }},
    { &hf_ansi_tcap_userInformation_01,
      { "userInformation", "ansi_tcap.userInformation",
        FT_UINT32, BASE_DEC, NULL, 0,
        "ansi_tcap.UserInformation", HFILL }},
    { &hf_ansi_tcap_securityContext,
      { "securityContext", "ansi_tcap.securityContext",
        FT_UINT32, BASE_DEC, VALS(ansi_tcap_T_securityContext_vals), 0,
        "ansi_tcap.T_securityContext", HFILL }},
    { &hf_ansi_tcap_integerSecurityId,
      { "integerSecurityId", "ansi_tcap.integerSecurityId",
        FT_INT32, BASE_DEC, NULL, 0,
        "ansi_tcap.INTEGER", HFILL }},
    { &hf_ansi_tcap_objectSecurityId,
      { "objectSecurityId", "ansi_tcap.objectSecurityId",
        FT_OID, BASE_NONE, NULL, 0,
        "ansi_tcap.OBJECT_IDENTIFIER", HFILL }},
    { &hf_ansi_tcap_confidentiality,
      { "confidentiality", "ansi_tcap.confidentiality",
        FT_NONE, BASE_NONE, NULL, 0,
        "ansi_tcap.Confidentiality", HFILL }},
    { &hf_ansi_tcap__untag_item,
      { "Item", "ansi_tcap._untag_item",
        FT_NONE, BASE_NONE, NULL, 0,
        "ansi_tcap.EXTERNAL", HFILL }},
    { &hf_ansi_tcap_confidentialityId,
      { "confidentialityId", "ansi_tcap.confidentialityId",
        FT_UINT32, BASE_DEC, VALS(ansi_tcap_T_confidentialityId_vals), 0,
        "ansi_tcap.T_confidentialityId", HFILL }},
    { &hf_ansi_tcap_integerConfidentialityId,
      { "integerConfidentialityId", "ansi_tcap.integerConfidentialityId",
        FT_INT32, BASE_DEC, NULL, 0,
        "ansi_tcap.INTEGER", HFILL }},
    { &hf_ansi_tcap_objectConfidentialityId,
      { "objectConfidentialityId", "ansi_tcap.objectConfidentialityId",
        FT_OID, BASE_NONE, NULL, 0,
        "ansi_tcap.OBJECT_IDENTIFIER", HFILL }},
    { &hf_ansi_tcap__untag_item_01,
      { "Item", "ansi_tcap._untag_item",
        FT_UINT32, BASE_DEC, VALS(ansi_tcap_ComponentPDU_vals), 0,
        "ansi_tcap.ComponentPDU", HFILL }},
    { &hf_ansi_tcap_invokeLast,
      { "invokeLast", "ansi_tcap.invokeLast",
        FT_NONE, BASE_NONE, NULL, 0,
        "ansi_tcap.Invoke", HFILL }},
    { &hf_ansi_tcap_returnResultLast,
      { "returnResultLast", "ansi_tcap.returnResultLast",
        FT_NONE, BASE_NONE, NULL, 0,
        "ansi_tcap.ReturnResult", HFILL }},
    { &hf_ansi_tcap_returnError,
      { "returnError", "ansi_tcap.returnError",
        FT_NONE, BASE_NONE, NULL, 0,
        "ansi_tcap.ReturnError", HFILL }},
    { &hf_ansi_tcap_reject,
      { "reject", "ansi_tcap.reject",
        FT_NONE, BASE_NONE, NULL, 0,
        "ansi_tcap.Reject", HFILL }},
    { &hf_ansi_tcap_invokeNotLast,
      { "invokeNotLast", "ansi_tcap.invokeNotLast",
        FT_NONE, BASE_NONE, NULL, 0,
        "ansi_tcap.Invoke", HFILL }},
    { &hf_ansi_tcap_returnResultNotLast,
      { "returnResultNotLast", "ansi_tcap.returnResultNotLast",
        FT_NONE, BASE_NONE, NULL, 0,
        "ansi_tcap.ReturnResult", HFILL }},
    { &hf_ansi_tcap_componentIDs,
      { "componentIDs", "ansi_tcap.componentIDs",
        FT_BYTES, BASE_HEX, NULL, 0,
        "ansi_tcap.T_componentIDs", HFILL }},
    { &hf_ansi_tcap_operationCode,
      { "operationCode", "ansi_tcap.operationCode",
        FT_UINT32, BASE_DEC, VALS(ansi_tcap_OperationCode_vals), 0,
        "ansi_tcap.OperationCode", HFILL }},
    { &hf_ansi_tcap_parameter,
      { "parameter", "ansi_tcap.parameter",
        FT_BYTES, BASE_HEX, NULL, 0,
        "ansi_tcap.T_parameter", HFILL }},
    { &hf_ansi_tcap_componentID,
      { "componentID", "ansi_tcap.componentID",
        FT_BYTES, BASE_HEX, NULL, 0,
        "ansi_tcap.T_componentID", HFILL }},
    { &hf_ansi_tcap_parameter_01,
      { "parameter", "ansi_tcap.parameter",
        FT_BYTES, BASE_HEX, NULL, 0,
        "ansi_tcap.T_parameter_01", HFILL }},
    { &hf_ansi_tcap_componentID_01,
      { "componentID", "ansi_tcap.componentID",
        FT_BYTES, BASE_HEX, NULL, 0,
        "ansi_tcap.T_componentID_01", HFILL }},
    { &hf_ansi_tcap_errorCode,
      { "errorCode", "ansi_tcap.errorCode",
        FT_UINT32, BASE_DEC, VALS(ansi_tcap_ErrorCode_vals), 0,
        "ansi_tcap.ErrorCode", HFILL }},
    { &hf_ansi_tcap_parameter_02,
      { "parameter", "ansi_tcap.parameter",
        FT_BYTES, BASE_HEX, NULL, 0,
        "ansi_tcap.T_parameter_02", HFILL }},
    { &hf_ansi_tcap_componentID_02,
      { "componentID", "ansi_tcap.componentID",
        FT_BYTES, BASE_HEX, NULL, 0,
        "ansi_tcap.OCTET_STRING_SIZE_0_1", HFILL }},
    { &hf_ansi_tcap_rejectProblem,
      { "rejectProblem", "ansi_tcap.rejectProblem",
        FT_INT32, BASE_DEC, VALS(ansi_tcap_Problem_vals), 0,
        "ansi_tcap.Problem", HFILL }},
    { &hf_ansi_tcap_parameter_03,
      { "parameter", "ansi_tcap.parameter",
        FT_UINT32, BASE_DEC, VALS(ansi_tcap_T_parameter_03_vals), 0,
        "ansi_tcap.T_parameter_03", HFILL }},
    { &hf_ansi_tcap_paramSequence,
      { "paramSequence", "ansi_tcap.paramSequence",
        FT_NONE, BASE_NONE, NULL, 0,
        "ansi_tcap.T_paramSequence", HFILL }},
    { &hf_ansi_tcap_paramSet,
      { "paramSet", "ansi_tcap.paramSet",
        FT_NONE, BASE_NONE, NULL, 0,
        "ansi_tcap.T_paramSet", HFILL }},

/
#line 453 "packet-ansi_tcap-template.c"
    };

/
    static gint *ett[] = {
	&ett_tcap,
	&ett_param,
	&ett_otid,
	&ett_dtid,
	&ett_ansi_tcap_stat,

/
#line 1 "packet-ansi_tcap-ettarr.c"
    &ett_ansi_tcap_OperationCode,
    &ett_ansi_tcap_ErrorCode,
    &ett_ansi_tcap_PackageType,
    &ett_ansi_tcap_UniTransactionPDU,
    &ett_ansi_tcap_TransactionPDU,
    &ett_ansi_tcap_Abort,
    &ett_ansi_tcap_T_causeInformation,
    &ett_ansi_tcap_DialoguePortion_U,
    &ett_ansi_tcap_T_applicationContext,
    &ett_ansi_tcap_T_securityContext,
    &ett_ansi_tcap_UserInformation_U,
    &ett_ansi_tcap_Confidentiality,
    &ett_ansi_tcap_T_confidentialityId,
    &ett_ansi_tcap_SEQUENCE_OF_ComponentPDU,
    &ett_ansi_tcap_ComponentPDU,
    &ett_ansi_tcap_Invoke,
    &ett_ansi_tcap_ReturnResult,
    &ett_ansi_tcap_ReturnError,
    &ett_ansi_tcap_Reject,
    &ett_ansi_tcap_T_parameter_03,
    &ett_ansi_tcap_T_paramSequence,
    &ett_ansi_tcap_T_paramSet,

/
#line 463 "packet-ansi_tcap-template.c"
    };

    /


/
    proto_ansi_tcap = proto_register_protocol(PNAME, PSNAME, PFNAME);
	register_dissector("ansi_tcap", dissect_ansi_tcap, proto_ansi_tcap);

/
    proto_register_field_array(proto_ansi_tcap, hf, array_length(hf));
    proto_register_subtree_array(ett, array_length(ett));


	register_init_routine(&ansi_tcap_init_protocol);
}
