static void dissect_r3_upstreammfgfield_cpuregisters (tvbuff_t *tvb, guint32 start_offset, guint32 length _U_, packet_info *pinfo _U_, proto_tree *tree)
{
  proto_tree *tmp_tree [19];
  proto_item *cr_item = proto_tree_add_text (tree, tvb, start_offset, -1, "CPU Registers");
  proto_tree *cr_tree = proto_item_add_subtree (cr_item, ett_r3cpuregisters);

  tmp_tree [ 0] = proto_item_add_subtree (proto_tree_add_item (cr_tree, hf_r3_cpuregisters_intcon,  tvb, start_offset +  0, 1, ENC_LITTLE_ENDIAN), ett_r3cpuregister);
  tmp_tree [ 1] = proto_item_add_subtree (proto_tree_add_item (cr_tree, hf_r3_cpuregisters_intcon2, tvb, start_offset +  1, 1, ENC_LITTLE_ENDIAN), ett_r3cpuregister);
  tmp_tree [ 2] = proto_item_add_subtree (proto_tree_add_item (cr_tree, hf_r3_cpuregisters_intcon3, tvb, start_offset +  2, 1, ENC_LITTLE_ENDIAN), ett_r3cpuregister);
  tmp_tree [ 3] = proto_item_add_subtree (proto_tree_add_item (cr_tree, hf_r3_cpuregisters_pir1,    tvb, start_offset +  3, 1, ENC_LITTLE_ENDIAN), ett_r3cpuregister);
  tmp_tree [ 4] = proto_item_add_subtree (proto_tree_add_item (cr_tree, hf_r3_cpuregisters_pir2,    tvb, start_offset +  4, 1, ENC_LITTLE_ENDIAN), ett_r3cpuregister);
  tmp_tree [ 5] = proto_item_add_subtree (proto_tree_add_item (cr_tree, hf_r3_cpuregisters_pir3,    tvb, start_offset +  5, 1, ENC_LITTLE_ENDIAN), ett_r3cpuregister);
  tmp_tree [ 6] = proto_item_add_subtree (proto_tree_add_item (cr_tree, hf_r3_cpuregisters_pie1,    tvb, start_offset +  6, 1, ENC_LITTLE_ENDIAN), ett_r3cpuregister);
  tmp_tree [ 7] = proto_item_add_subtree (proto_tree_add_item (cr_tree, hf_r3_cpuregisters_pie2,    tvb, start_offset +  7, 1, ENC_LITTLE_ENDIAN), ett_r3cpuregister);
  tmp_tree [ 8] = proto_item_add_subtree (proto_tree_add_item (cr_tree, hf_r3_cpuregisters_pie3,    tvb, start_offset +  8, 1, ENC_LITTLE_ENDIAN), ett_r3cpuregister);
  tmp_tree [ 9] = proto_item_add_subtree (proto_tree_add_item (cr_tree, hf_r3_cpuregisters_ipr1,    tvb, start_offset +  9, 1, ENC_LITTLE_ENDIAN), ett_r3cpuregister);
  tmp_tree [10] = proto_item_add_subtree (proto_tree_add_item (cr_tree, hf_r3_cpuregisters_ipr2,    tvb, start_offset + 10, 1, ENC_LITTLE_ENDIAN), ett_r3cpuregister);
  tmp_tree [11] = proto_item_add_subtree (proto_tree_add_item (cr_tree, hf_r3_cpuregisters_ipr3,    tvb, start_offset + 11, 1, ENC_LITTLE_ENDIAN), ett_r3cpuregister);
  tmp_tree [12] = proto_item_add_subtree (proto_tree_add_item (cr_tree, hf_r3_cpuregisters_rcon,    tvb, start_offset + 12, 1, ENC_LITTLE_ENDIAN), ett_r3cpuregister);
  tmp_tree [13] = proto_item_add_subtree (proto_tree_add_item (cr_tree, hf_r3_cpuregisters_osccon,  tvb, start_offset + 13, 1, ENC_LITTLE_ENDIAN), ett_r3cpuregister);
  tmp_tree [14] = proto_item_add_subtree (proto_tree_add_item (cr_tree, hf_r3_cpuregisters_rcsta,   tvb, start_offset + 14, 1, ENC_LITTLE_ENDIAN), ett_r3cpuregister);
  tmp_tree [15] = proto_item_add_subtree (proto_tree_add_item (cr_tree, hf_r3_cpuregisters_txsta,   tvb, start_offset + 15, 1, ENC_LITTLE_ENDIAN), ett_r3cpuregister);
  tmp_tree [16] = proto_item_add_subtree (proto_tree_add_item (cr_tree, hf_r3_cpuregisters_rcsta2,  tvb, start_offset + 16, 1, ENC_LITTLE_ENDIAN), ett_r3cpuregister);
  tmp_tree [17] = proto_item_add_subtree (proto_tree_add_item (cr_tree, hf_r3_cpuregisters_txsta2,  tvb, start_offset + 17, 1, ENC_LITTLE_ENDIAN), ett_r3cpuregister);
  tmp_tree [18] = proto_item_add_subtree (proto_tree_add_item (cr_tree, hf_r3_cpuregisters_wdtcon,  tvb, start_offset + 18, 1, ENC_LITTLE_ENDIAN), ett_r3cpuregister);

  proto_tree_add_boolean (tmp_tree [ 0], hf_r3_cpuregisters_intcon_rbif,     tvb, start_offset +  0, 1, tvb_get_guint8 (tvb, start_offset +  0));
  proto_tree_add_boolean (tmp_tree [ 0], hf_r3_cpuregisters_intcon_int0if,   tvb, start_offset +  0, 1, tvb_get_guint8 (tvb, start_offset +  0));
  proto_tree_add_boolean (tmp_tree [ 0], hf_r3_cpuregisters_intcon_tmr0if,   tvb, start_offset +  0, 1, tvb_get_guint8 (tvb, start_offset +  0));
  proto_tree_add_boolean (tmp_tree [ 0], hf_r3_cpuregisters_intcon_rbie,     tvb, start_offset +  0, 1, tvb_get_guint8 (tvb, start_offset +  0));
  proto_tree_add_boolean (tmp_tree [ 0], hf_r3_cpuregisters_intcon_int0ie,   tvb, start_offset +  0, 1, tvb_get_guint8 (tvb, start_offset +  0));
  proto_tree_add_boolean (tmp_tree [ 0], hf_r3_cpuregisters_intcon_tmr0ie,   tvb, start_offset +  0, 1, tvb_get_guint8 (tvb, start_offset +  0));
  proto_tree_add_boolean (tmp_tree [ 0], hf_r3_cpuregisters_intcon_giel,     tvb, start_offset +  0, 1, tvb_get_guint8 (tvb, start_offset +  0));
  proto_tree_add_boolean (tmp_tree [ 0], hf_r3_cpuregisters_intcon_gieh,     tvb, start_offset +  0, 1, tvb_get_guint8 (tvb, start_offset +  0));
  proto_tree_add_boolean (tmp_tree [ 1], hf_r3_cpuregisters_intcon2_rbip,    tvb, start_offset +  1, 1, tvb_get_guint8 (tvb, start_offset +  1));
  proto_tree_add_boolean (tmp_tree [ 1], hf_r3_cpuregisters_intcon2_int3ip,  tvb, start_offset +  1, 1, tvb_get_guint8 (tvb, start_offset +  1));
  proto_tree_add_boolean (tmp_tree [ 1], hf_r3_cpuregisters_intcon2_tmr0ip,  tvb, start_offset +  1, 1, tvb_get_guint8 (tvb, start_offset +  1));
  proto_tree_add_boolean (tmp_tree [ 1], hf_r3_cpuregisters_intcon2_intedg3, tvb, start_offset +  1, 1, tvb_get_guint8 (tvb, start_offset +  1));
  proto_tree_add_boolean (tmp_tree [ 1], hf_r3_cpuregisters_intcon2_intedg2, tvb, start_offset +  1, 1, tvb_get_guint8 (tvb, start_offset +  1));
  proto_tree_add_boolean (tmp_tree [ 1], hf_r3_cpuregisters_intcon2_intedg1, tvb, start_offset +  1, 1, tvb_get_guint8 (tvb, start_offset +  1));
  proto_tree_add_boolean (tmp_tree [ 1], hf_r3_cpuregisters_intcon2_intedg0, tvb, start_offset +  1, 1, tvb_get_guint8 (tvb, start_offset +  1));
  proto_tree_add_boolean (tmp_tree [ 1], hf_r3_cpuregisters_intcon2_rbpu,    tvb, start_offset +  1, 1, tvb_get_guint8 (tvb, start_offset +  1));
  proto_tree_add_boolean (tmp_tree [ 2], hf_r3_cpuregisters_intcon3_int1if,  tvb, start_offset +  2, 1, tvb_get_guint8 (tvb, start_offset +  2));
  proto_tree_add_boolean (tmp_tree [ 2], hf_r3_cpuregisters_intcon3_int2if,  tvb, start_offset +  2, 1, tvb_get_guint8 (tvb, start_offset +  2));
  proto_tree_add_boolean (tmp_tree [ 2], hf_r3_cpuregisters_intcon3_int3if,  tvb, start_offset +  2, 1, tvb_get_guint8 (tvb, start_offset +  2));
  proto_tree_add_boolean (tmp_tree [ 2], hf_r3_cpuregisters_intcon3_int1ie,  tvb, start_offset +  2, 1, tvb_get_guint8 (tvb, start_offset +  2));
  proto_tree_add_boolean (tmp_tree [ 2], hf_r3_cpuregisters_intcon3_int2ie,  tvb, start_offset +  2, 1, tvb_get_guint8 (tvb, start_offset +  2));
  proto_tree_add_boolean (tmp_tree [ 2], hf_r3_cpuregisters_intcon3_int3ie,  tvb, start_offset +  2, 1, tvb_get_guint8 (tvb, start_offset +  2));
  proto_tree_add_boolean (tmp_tree [ 2], hf_r3_cpuregisters_intcon3_int1ip,  tvb, start_offset +  2, 1, tvb_get_guint8 (tvb, start_offset +  2));
  proto_tree_add_boolean (tmp_tree [ 2], hf_r3_cpuregisters_intcon3_int2ip,  tvb, start_offset +  2, 1, tvb_get_guint8 (tvb, start_offset +  2));
  proto_tree_add_boolean (tmp_tree [ 3], hf_r3_cpuregisters_pir1_tmr1if,     tvb, start_offset +  3, 1, tvb_get_guint8 (tvb, start_offset +  3));
  proto_tree_add_boolean (tmp_tree [ 3], hf_r3_cpuregisters_pir1_tmr2if,     tvb, start_offset +  3, 1, tvb_get_guint8 (tvb, start_offset +  3));
  proto_tree_add_boolean (tmp_tree [ 3], hf_r3_cpuregisters_pir1_ccp1if,     tvb, start_offset +  3, 1, tvb_get_guint8 (tvb, start_offset +  3));
  proto_tree_add_boolean (tmp_tree [ 3], hf_r3_cpuregisters_pir1_ssp1if,     tvb, start_offset +  3, 1, tvb_get_guint8 (tvb, start_offset +  3));
  proto_tree_add_boolean (tmp_tree [ 3], hf_r3_cpuregisters_pir1_tx1if,      tvb, start_offset +  3, 1, tvb_get_guint8 (tvb, start_offset +  3));
  proto_tree_add_boolean (tmp_tree [ 3], hf_r3_cpuregisters_pir1_rc1if,      tvb, start_offset +  3, 1, tvb_get_guint8 (tvb, start_offset +  3));
  proto_tree_add_boolean (tmp_tree [ 3], hf_r3_cpuregisters_pir1_adif,       tvb, start_offset +  3, 1, tvb_get_guint8 (tvb, start_offset +  3));
  proto_tree_add_boolean (tmp_tree [ 3], hf_r3_cpuregisters_pir1_pspif,      tvb, start_offset +  3, 1, tvb_get_guint8 (tvb, start_offset +  3));
  proto_tree_add_boolean (tmp_tree [ 4], hf_r3_cpuregisters_pir2_ccp2if,     tvb, start_offset +  4, 1, tvb_get_guint8 (tvb, start_offset +  4));
  proto_tree_add_boolean (tmp_tree [ 4], hf_r3_cpuregisters_pir2_tmr3if,     tvb, start_offset +  4, 1, tvb_get_guint8 (tvb, start_offset +  4));
  proto_tree_add_boolean (tmp_tree [ 4], hf_r3_cpuregisters_pir2_hlvdif,     tvb, start_offset +  4, 1, tvb_get_guint8 (tvb, start_offset +  4));
  proto_tree_add_boolean (tmp_tree [ 4], hf_r3_cpuregisters_pir2_bcl1if,     tvb, start_offset +  4, 1, tvb_get_guint8 (tvb, start_offset +  4));
  proto_tree_add_boolean (tmp_tree [ 4], hf_r3_cpuregisters_pir2_eeif,       tvb, start_offset +  4, 1, tvb_get_guint8 (tvb, start_offset +  4));
  proto_tree_add_boolean (tmp_tree [ 4], hf_r3_cpuregisters_pir2_unused5,    tvb, start_offset +  4, 1, tvb_get_guint8 (tvb, start_offset +  4));
  proto_tree_add_boolean (tmp_tree [ 4], hf_r3_cpuregisters_pir2_cmif,       tvb, start_offset +  4, 1, tvb_get_guint8 (tvb, start_offset +  4));
  proto_tree_add_boolean (tmp_tree [ 4], hf_r3_cpuregisters_pir2_oscfif,     tvb, start_offset +  4, 1, tvb_get_guint8 (tvb, start_offset +  4));
  proto_tree_add_boolean (tmp_tree [ 5], hf_r3_cpuregisters_pir3_ccp3if,     tvb, start_offset +  5, 1, tvb_get_guint8 (tvb, start_offset +  5));
  proto_tree_add_boolean (tmp_tree [ 5], hf_r3_cpuregisters_pir3_ccp4if,     tvb, start_offset +  5, 1, tvb_get_guint8 (tvb, start_offset +  5));
  proto_tree_add_boolean (tmp_tree [ 5], hf_r3_cpuregisters_pir3_ccp5if,     tvb, start_offset +  5, 1, tvb_get_guint8 (tvb, start_offset +  5));
  proto_tree_add_boolean (tmp_tree [ 5], hf_r3_cpuregisters_pir3_tmr4if,     tvb, start_offset +  5, 1, tvb_get_guint8 (tvb, start_offset +  5));
  proto_tree_add_boolean (tmp_tree [ 5], hf_r3_cpuregisters_pir3_tx2if,      tvb, start_offset +  5, 1, tvb_get_guint8 (tvb, start_offset +  5));
  proto_tree_add_boolean (tmp_tree [ 5], hf_r3_cpuregisters_pir3_rc2if,      tvb, start_offset +  5, 1, tvb_get_guint8 (tvb, start_offset +  5));
  proto_tree_add_boolean (tmp_tree [ 5], hf_r3_cpuregisters_pir3_bcl2if,     tvb, start_offset +  5, 1, tvb_get_guint8 (tvb, start_offset +  5));
  proto_tree_add_boolean (tmp_tree [ 5], hf_r3_cpuregisters_pir3_ssp2if,     tvb, start_offset +  5, 1, tvb_get_guint8 (tvb, start_offset +  5));
  proto_tree_add_boolean (tmp_tree [ 6], hf_r3_cpuregisters_pie1_tmr1ie,     tvb, start_offset +  6, 1, tvb_get_guint8 (tvb, start_offset +  6));
  proto_tree_add_boolean (tmp_tree [ 6], hf_r3_cpuregisters_pie1_tmr2ie,     tvb, start_offset +  6, 1, tvb_get_guint8 (tvb, start_offset +  6));
  proto_tree_add_boolean (tmp_tree [ 6], hf_r3_cpuregisters_pie1_ccp1ie,     tvb, start_offset +  6, 1, tvb_get_guint8 (tvb, start_offset +  6));
  proto_tree_add_boolean (tmp_tree [ 6], hf_r3_cpuregisters_pie1_ssp1ie,     tvb, start_offset +  6, 1, tvb_get_guint8 (tvb, start_offset +  6));
  proto_tree_add_boolean (tmp_tree [ 6], hf_r3_cpuregisters_pie1_tx1ie,      tvb, start_offset +  6, 1, tvb_get_guint8 (tvb, start_offset +  6));
  proto_tree_add_boolean (tmp_tree [ 6], hf_r3_cpuregisters_pie1_rc1ie,      tvb, start_offset +  6, 1, tvb_get_guint8 (tvb, start_offset +  6));
  proto_tree_add_boolean (tmp_tree [ 6], hf_r3_cpuregisters_pie1_adie,       tvb, start_offset +  6, 1, tvb_get_guint8 (tvb, start_offset +  6));
  proto_tree_add_boolean (tmp_tree [ 6], hf_r3_cpuregisters_pie1_pspie,      tvb, start_offset +  6, 1, tvb_get_guint8 (tvb, start_offset +  6));
  proto_tree_add_boolean (tmp_tree [ 7], hf_r3_cpuregisters_pie2_oscfie,     tvb, start_offset +  7, 1, tvb_get_guint8 (tvb, start_offset +  7));
  proto_tree_add_boolean (tmp_tree [ 7], hf_r3_cpuregisters_pie2_cmie,       tvb, start_offset +  7, 1, tvb_get_guint8 (tvb, start_offset +  7));
  proto_tree_add_boolean (tmp_tree [ 7], hf_r3_cpuregisters_pie2_unused2,    tvb, start_offset +  7, 1, tvb_get_guint8 (tvb, start_offset +  7));
  proto_tree_add_boolean (tmp_tree [ 7], hf_r3_cpuregisters_pie2_eeie,       tvb, start_offset +  7, 1, tvb_get_guint8 (tvb, start_offset +  7));
  proto_tree_add_boolean (tmp_tree [ 7], hf_r3_cpuregisters_pie2_bcl1ie,     tvb, start_offset +  7, 1, tvb_get_guint8 (tvb, start_offset +  7));
  proto_tree_add_boolean (tmp_tree [ 7], hf_r3_cpuregisters_pie2_hlvdie,     tvb, start_offset +  7, 1, tvb_get_guint8 (tvb, start_offset +  7));
  proto_tree_add_boolean (tmp_tree [ 7], hf_r3_cpuregisters_pie2_tmr3ie,     tvb, start_offset +  7, 1, tvb_get_guint8 (tvb, start_offset +  7));
  proto_tree_add_boolean (tmp_tree [ 7], hf_r3_cpuregisters_pie2_ccp2ie,     tvb, start_offset +  7, 1, tvb_get_guint8 (tvb, start_offset +  7));
  proto_tree_add_boolean (tmp_tree [ 8], hf_r3_cpuregisters_pie3_ccp3ie,     tvb, start_offset +  8, 1, tvb_get_guint8 (tvb, start_offset +  8));
  proto_tree_add_boolean (tmp_tree [ 8], hf_r3_cpuregisters_pie3_ccp4ie,     tvb, start_offset +  8, 1, tvb_get_guint8 (tvb, start_offset +  8));
  proto_tree_add_boolean (tmp_tree [ 8], hf_r3_cpuregisters_pie3_ccp5ie,     tvb, start_offset +  8, 1, tvb_get_guint8 (tvb, start_offset +  8));
  proto_tree_add_boolean (tmp_tree [ 8], hf_r3_cpuregisters_pie3_tmr4ie,     tvb, start_offset +  8, 1, tvb_get_guint8 (tvb, start_offset +  8));
  proto_tree_add_boolean (tmp_tree [ 8], hf_r3_cpuregisters_pie3_tx2ie,      tvb, start_offset +  8, 1, tvb_get_guint8 (tvb, start_offset +  8));
  proto_tree_add_boolean (tmp_tree [ 8], hf_r3_cpuregisters_pie3_rc2ie,      tvb, start_offset +  8, 1, tvb_get_guint8 (tvb, start_offset +  8));
  proto_tree_add_boolean (tmp_tree [ 8], hf_r3_cpuregisters_pie3_bcl2ie,     tvb, start_offset +  8, 1, tvb_get_guint8 (tvb, start_offset +  8));
  proto_tree_add_boolean (tmp_tree [ 8], hf_r3_cpuregisters_pie3_ssp2ie,     tvb, start_offset +  8, 1, tvb_get_guint8 (tvb, start_offset +  8));
  proto_tree_add_boolean (tmp_tree [ 9], hf_r3_cpuregisters_ipr1_tmr1ip,     tvb, start_offset +  9, 1, tvb_get_guint8 (tvb, start_offset +  9));
  proto_tree_add_boolean (tmp_tree [ 9], hf_r3_cpuregisters_ipr1_tmr2ip,     tvb, start_offset +  9, 1, tvb_get_guint8 (tvb, start_offset +  9));
  proto_tree_add_boolean (tmp_tree [ 9], hf_r3_cpuregisters_ipr1_ccp1ip,     tvb, start_offset +  9, 1, tvb_get_guint8 (tvb, start_offset +  9));
  proto_tree_add_boolean (tmp_tree [ 9], hf_r3_cpuregisters_ipr1_ssp1ip,     tvb, start_offset +  9, 1, tvb_get_guint8 (tvb, start_offset +  9));
  proto_tree_add_boolean (tmp_tree [ 9], hf_r3_cpuregisters_ipr1_tx1ip,      tvb, start_offset +  9, 1, tvb_get_guint8 (tvb, start_offset +  9));
  proto_tree_add_boolean (tmp_tree [ 9], hf_r3_cpuregisters_ipr1_rc1ip,      tvb, start_offset +  9, 1, tvb_get_guint8 (tvb, start_offset +  9));
  proto_tree_add_boolean (tmp_tree [ 9], hf_r3_cpuregisters_ipr1_adip,       tvb, start_offset +  9, 1, tvb_get_guint8 (tvb, start_offset +  9));
  proto_tree_add_boolean (tmp_tree [ 9], hf_r3_cpuregisters_ipr1_pspip,      tvb, start_offset +  9, 1, tvb_get_guint8 (tvb, start_offset +  9));
  proto_tree_add_boolean (tmp_tree [10], hf_r3_cpuregisters_ipr2_ccp2ip,     tvb, start_offset + 10, 1, tvb_get_guint8 (tvb, start_offset + 10));
  proto_tree_add_boolean (tmp_tree [10], hf_r3_cpuregisters_ipr2_tmr3ip,     tvb, start_offset + 10, 1, tvb_get_guint8 (tvb, start_offset + 10));
  proto_tree_add_boolean (tmp_tree [10], hf_r3_cpuregisters_ipr2_hlvdip,     tvb, start_offset + 10, 1, tvb_get_guint8 (tvb, start_offset + 10));
  proto_tree_add_boolean (tmp_tree [10], hf_r3_cpuregisters_ipr2_bcl1ip,     tvb, start_offset + 10, 1, tvb_get_guint8 (tvb, start_offset + 10));
  proto_tree_add_boolean (tmp_tree [10], hf_r3_cpuregisters_ipr2_eeip,       tvb, start_offset + 10, 1, tvb_get_guint8 (tvb, start_offset + 10));
  proto_tree_add_boolean (tmp_tree [10], hf_r3_cpuregisters_ipr2_unused5,    tvb, start_offset + 10, 1, tvb_get_guint8 (tvb, start_offset + 10));
  proto_tree_add_boolean (tmp_tree [10], hf_r3_cpuregisters_ipr2_cmip,       tvb, start_offset + 10, 1, tvb_get_guint8 (tvb, start_offset + 10));
  proto_tree_add_boolean (tmp_tree [10], hf_r3_cpuregisters_ipr2_oscfip,     tvb, start_offset + 10, 1, tvb_get_guint8 (tvb, start_offset + 10));
  proto_tree_add_boolean (tmp_tree [11], hf_r3_cpuregisters_ipr3_ccp2ip,     tvb, start_offset + 11, 1, tvb_get_guint8 (tvb, start_offset + 11));
  proto_tree_add_boolean (tmp_tree [11], hf_r3_cpuregisters_ipr3_ccp4ip,     tvb, start_offset + 11, 1, tvb_get_guint8 (tvb, start_offset + 11));
  proto_tree_add_boolean (tmp_tree [11], hf_r3_cpuregisters_ipr3_ccp5ip,     tvb, start_offset + 11, 1, tvb_get_guint8 (tvb, start_offset + 11));
  proto_tree_add_boolean (tmp_tree [11], hf_r3_cpuregisters_ipr3_tmr4ip,     tvb, start_offset + 11, 1, tvb_get_guint8 (tvb, start_offset + 11));
  proto_tree_add_boolean (tmp_tree [11], hf_r3_cpuregisters_ipr3_tx2ip,      tvb, start_offset + 11, 1, tvb_get_guint8 (tvb, start_offset + 11));
  proto_tree_add_boolean (tmp_tree [11], hf_r3_cpuregisters_ipr3_rc2ip,      tvb, start_offset + 11, 1, tvb_get_guint8 (tvb, start_offset + 11));
  proto_tree_add_boolean (tmp_tree [11], hf_r3_cpuregisters_ipr3_bcl2ip,     tvb, start_offset + 11, 1, tvb_get_guint8 (tvb, start_offset + 11));
  proto_tree_add_boolean (tmp_tree [11], hf_r3_cpuregisters_ipr3_ssp2ip,     tvb, start_offset + 11, 1, tvb_get_guint8 (tvb, start_offset + 11));
  proto_tree_add_boolean (tmp_tree [12], hf_r3_cpuregisters_rcon_bor,        tvb, start_offset + 12, 1, tvb_get_guint8 (tvb, start_offset + 12));
  proto_tree_add_boolean (tmp_tree [12], hf_r3_cpuregisters_rcon_por,        tvb, start_offset + 12, 1, tvb_get_guint8 (tvb, start_offset + 12));
  proto_tree_add_boolean (tmp_tree [12], hf_r3_cpuregisters_rcon_pd,         tvb, start_offset + 12, 1, tvb_get_guint8 (tvb, start_offset + 12));
  proto_tree_add_boolean (tmp_tree [12], hf_r3_cpuregisters_rcon_to,         tvb, start_offset + 12, 1, tvb_get_guint8 (tvb, start_offset + 12));
  proto_tree_add_boolean (tmp_tree [12], hf_r3_cpuregisters_rcon_unused4,    tvb, start_offset + 12, 1, tvb_get_guint8 (tvb, start_offset + 12));
  proto_tree_add_boolean (tmp_tree [12], hf_r3_cpuregisters_rcon_ri,         tvb, start_offset + 12, 1, tvb_get_guint8 (tvb, start_offset + 12));
  proto_tree_add_boolean (tmp_tree [12], hf_r3_cpuregisters_rcon_sboren,     tvb, start_offset + 12, 1, tvb_get_guint8 (tvb, start_offset + 12));
  proto_tree_add_boolean (tmp_tree [12], hf_r3_cpuregisters_rcon_ipen,       tvb, start_offset + 12, 1, tvb_get_guint8 (tvb, start_offset + 12));
  proto_tree_add_boolean (tmp_tree [13], hf_r3_cpuregisters_osccon_scs0,     tvb, start_offset + 13, 1, tvb_get_guint8 (tvb, start_offset + 13));
  proto_tree_add_boolean (tmp_tree [13], hf_r3_cpuregisters_osccon_scs1,     tvb, start_offset + 13, 1, tvb_get_guint8 (tvb, start_offset + 13));
  proto_tree_add_boolean (tmp_tree [13], hf_r3_cpuregisters_osccon_iofs,     tvb, start_offset + 13, 1, tvb_get_guint8 (tvb, start_offset + 13));
  proto_tree_add_boolean (tmp_tree [13], hf_r3_cpuregisters_osccon_osts,     tvb, start_offset + 13, 1, tvb_get_guint8 (tvb, start_offset + 13));
  proto_tree_add_boolean (tmp_tree [13], hf_r3_cpuregisters_osccon_ircf0,    tvb, start_offset + 13, 1, tvb_get_guint8 (tvb, start_offset + 13));
  proto_tree_add_boolean (tmp_tree [13], hf_r3_cpuregisters_osccon_ircf1,    tvb, start_offset + 13, 1, tvb_get_guint8 (tvb, start_offset + 13));
  proto_tree_add_boolean (tmp_tree [13], hf_r3_cpuregisters_osccon_ircf2,    tvb, start_offset + 13, 1, tvb_get_guint8 (tvb, start_offset + 13));
  proto_tree_add_boolean (tmp_tree [13], hf_r3_cpuregisters_osccon_idlen,    tvb, start_offset + 13, 1, tvb_get_guint8 (tvb, start_offset + 13));
  proto_tree_add_boolean (tmp_tree [14], hf_r3_cpuregisters_rcsta_rx9d,      tvb, start_offset + 14, 1, tvb_get_guint8 (tvb, start_offset + 14));
  proto_tree_add_boolean (tmp_tree [14], hf_r3_cpuregisters_rcsta_oerr,      tvb, start_offset + 14, 1, tvb_get_guint8 (tvb, start_offset + 14));
  proto_tree_add_boolean (tmp_tree [14], hf_r3_cpuregisters_rcsta_ferr,      tvb, start_offset + 14, 1, tvb_get_guint8 (tvb, start_offset + 14));
  proto_tree_add_boolean (tmp_tree [14], hf_r3_cpuregisters_rcsta_adden,     tvb, start_offset + 14, 1, tvb_get_guint8 (tvb, start_offset + 14));
  proto_tree_add_boolean (tmp_tree [14], hf_r3_cpuregisters_rcsta_cren,      tvb, start_offset + 14, 1, tvb_get_guint8 (tvb, start_offset + 14));
  proto_tree_add_boolean (tmp_tree [14], hf_r3_cpuregisters_rcsta_sren,      tvb, start_offset + 14, 1, tvb_get_guint8 (tvb, start_offset + 14));
  proto_tree_add_boolean (tmp_tree [14], hf_r3_cpuregisters_rcsta_rx9,       tvb, start_offset + 14, 1, tvb_get_guint8 (tvb, start_offset + 14));
  proto_tree_add_boolean (tmp_tree [14], hf_r3_cpuregisters_rcsta_spen,      tvb, start_offset + 14, 1, tvb_get_guint8 (tvb, start_offset + 14));
  proto_tree_add_boolean (tmp_tree [15], hf_r3_cpuregisters_txsta_tx9d,      tvb, start_offset + 15, 1, tvb_get_guint8 (tvb, start_offset + 15));
  proto_tree_add_boolean (tmp_tree [15], hf_r3_cpuregisters_txsta_trmt,      tvb, start_offset + 15, 1, tvb_get_guint8 (tvb, start_offset + 15));
  proto_tree_add_boolean (tmp_tree [15], hf_r3_cpuregisters_txsta_brgh,      tvb, start_offset + 15, 1, tvb_get_guint8 (tvb, start_offset + 15));
  proto_tree_add_boolean (tmp_tree [15], hf_r3_cpuregisters_txsta_sendb,     tvb, start_offset + 15, 1, tvb_get_guint8 (tvb, start_offset + 15));
  proto_tree_add_boolean (tmp_tree [15], hf_r3_cpuregisters_txsta_sync,      tvb, start_offset + 15, 1, tvb_get_guint8 (tvb, start_offset + 15));
  proto_tree_add_boolean (tmp_tree [15], hf_r3_cpuregisters_txsta_txen,      tvb, start_offset + 15, 1, tvb_get_guint8 (tvb, start_offset + 15));
  proto_tree_add_boolean (tmp_tree [15], hf_r3_cpuregisters_txsta_tx9,       tvb, start_offset + 15, 1, tvb_get_guint8 (tvb, start_offset + 15));
  proto_tree_add_boolean (tmp_tree [15], hf_r3_cpuregisters_txsta_csrc,      tvb, start_offset + 15, 1, tvb_get_guint8 (tvb, start_offset + 15));
  proto_tree_add_boolean (tmp_tree [16], hf_r3_cpuregisters_rcsta2_rx9d,     tvb, start_offset + 16, 1, tvb_get_guint8 (tvb, start_offset + 16));
  proto_tree_add_boolean (tmp_tree [16], hf_r3_cpuregisters_rcsta2_oerr,     tvb, start_offset + 16, 1, tvb_get_guint8 (tvb, start_offset + 16));
  proto_tree_add_boolean (tmp_tree [16], hf_r3_cpuregisters_rcsta2_ferr,     tvb, start_offset + 16, 1, tvb_get_guint8 (tvb, start_offset + 16));
  proto_tree_add_boolean (tmp_tree [16], hf_r3_cpuregisters_rcsta2_adden,    tvb, start_offset + 16, 1, tvb_get_guint8 (tvb, start_offset + 16));
  proto_tree_add_boolean (tmp_tree [16], hf_r3_cpuregisters_rcsta2_cren,     tvb, start_offset + 16, 1, tvb_get_guint8 (tvb, start_offset + 16));
  proto_tree_add_boolean (tmp_tree [16], hf_r3_cpuregisters_rcsta2_sren,     tvb, start_offset + 16, 1, tvb_get_guint8 (tvb, start_offset + 16));
  proto_tree_add_boolean (tmp_tree [16], hf_r3_cpuregisters_rcsta2_rx9,      tvb, start_offset + 16, 1, tvb_get_guint8 (tvb, start_offset + 16));
  proto_tree_add_boolean (tmp_tree [16], hf_r3_cpuregisters_rcsta2_spen,     tvb, start_offset + 16, 1, tvb_get_guint8 (tvb, start_offset + 16));
  proto_tree_add_boolean (tmp_tree [17], hf_r3_cpuregisters_txsta2_tx9d,     tvb, start_offset + 17, 1, tvb_get_guint8 (tvb, start_offset + 17));
  proto_tree_add_boolean (tmp_tree [17], hf_r3_cpuregisters_txsta2_trmt,     tvb, start_offset + 17, 1, tvb_get_guint8 (tvb, start_offset + 17));
  proto_tree_add_boolean (tmp_tree [17], hf_r3_cpuregisters_txsta2_brgh,     tvb, start_offset + 17, 1, tvb_get_guint8 (tvb, start_offset + 17));
  proto_tree_add_boolean (tmp_tree [17], hf_r3_cpuregisters_txsta2_sendb,    tvb, start_offset + 17, 1, tvb_get_guint8 (tvb, start_offset + 17));
  proto_tree_add_boolean (tmp_tree [17], hf_r3_cpuregisters_txsta2_sync,     tvb, start_offset + 17, 1, tvb_get_guint8 (tvb, start_offset + 17));
  proto_tree_add_boolean (tmp_tree [17], hf_r3_cpuregisters_txsta2_txen,     tvb, start_offset + 17, 1, tvb_get_guint8 (tvb, start_offset + 17));
  proto_tree_add_boolean (tmp_tree [17], hf_r3_cpuregisters_txsta2_tx9,      tvb, start_offset + 17, 1, tvb_get_guint8 (tvb, start_offset + 17));
  proto_tree_add_boolean (tmp_tree [17], hf_r3_cpuregisters_txsta2_csrc,     tvb, start_offset + 17, 1, tvb_get_guint8 (tvb, start_offset + 17));
  proto_tree_add_boolean (tmp_tree [18], hf_r3_cpuregisters_wdtcon_swdten,   tvb, start_offset + 18, 1, tvb_get_guint8 (tvb, start_offset + 18));
  proto_tree_add_boolean (tmp_tree [18], hf_r3_cpuregisters_wdtcon_unused1,  tvb, start_offset + 18, 1, tvb_get_guint8 (tvb, start_offset + 18));
  proto_tree_add_boolean (tmp_tree [18], hf_r3_cpuregisters_wdtcon_unused2,  tvb, start_offset + 18, 1, tvb_get_guint8 (tvb, start_offset + 18));
  proto_tree_add_boolean (tmp_tree [18], hf_r3_cpuregisters_wdtcon_unused3,  tvb, start_offset + 18, 1, tvb_get_guint8 (tvb, start_offset + 18));
  proto_tree_add_boolean (tmp_tree [18], hf_r3_cpuregisters_wdtcon_unused4,  tvb, start_offset + 18, 1, tvb_get_guint8 (tvb, start_offset + 18));
  proto_tree_add_boolean (tmp_tree [18], hf_r3_cpuregisters_wdtcon_unused5,  tvb, start_offset + 18, 1, tvb_get_guint8 (tvb, start_offset + 18));
  proto_tree_add_boolean (tmp_tree [18], hf_r3_cpuregisters_wdtcon_unused6,  tvb, start_offset + 18, 1, tvb_get_guint8 (tvb, start_offset + 18));
  proto_tree_add_boolean (tmp_tree [18], hf_r3_cpuregisters_wdtcon_unused7,  tvb, start_offset + 18, 1, tvb_get_guint8 (tvb, start_offset + 18));
}
